version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  target-branch: "develop"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - duttonw
  - qld-gov-au/qld-online-dev-team
