# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Chromatic

on:
  # push:
  # pull_request:

concurrency:
  group: compile-${{ github.workflow }}-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    name: Build and Deploy on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install #run on lint step (Which is cached)
        run: | # Install packages
          npm install --prefer-offline --no-audit
      - name: Build 🔧
        run: |
          npm run build
      - name: Test 🔧
        run: |
          npm run watch &
          echo "sleeping 10"; sleep 10;
          npm run test
      - name: Build Storybook 🔧
        run: |
          npm run build-storybook
      - name: Chromatic 🔧
        run: | # publish Storybook and run visual tests
          npm run chromatic
