# This workflow is for Chromatic trial run, deploy to a trial Chromatic account, for official implementation, please replace the CHROMATIC_PROJECT_TOKEN in Github secrets.

# Further details on Chromatic setup: https://www.chromatic.com/docs/github-actions

name: Publish Chromatic

on:
  workflow_run:
    workflows: [Build and Test Release] # Reuse the name of your tests workflow
    types:
      - completed

concurrency:
  group: compile-${{ github.workflow }}-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    name: Build and Deploy on Node ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install #run on lint step (Which is cached)
        run: | # Install packages
          npm install --prefer-offline --no-audit
      - name: Build 🔧
        run: |
          npm run build
      - name: Build Storybook 🔧
        run: |
          npm run build-storybook-ci
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Options required to the GitHub Chromatic Action
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: "storybook-static"
